# Generated by Django 5.1.2 on 2024-10-30 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=250,
                validators=[django.core.validators.MinLengthValidator(8)],
            ),
        ),
    ]
