# Generated by Django 5.1.2 on 2024-11-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_loan_aproved_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("em aberto", "Em Aberto"),
                    ("concluído", "Concluido"),
                ],
                default="pendente",
            ),
        ),
    ]
